{{- define "common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name}}
type: Opaque
data:
  {{- if .Values.global.githubpass.enabled }}
  GITHUB_PASSWORD: {{ .Values.secret.githubPass }}
  {{- end }}
  {{- if .Values.global.postgresuser.enabled }}
  POSTGRES_USER: {{ .Values.secret.postgresUser }}
  {{- end }}
  {{- if .Values.global.postgrespass.enabled }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPass }}
  {{- end }}
  {{- if .Values.global.dbuser.enabled }}
  DB_USER: {{ .Values.secret.dbUser }}
  {{- end }}
  {{- if .Values.global.dbpass.enabled }}
  DB_PASS: {{ .Values.secret.dbPass }}
  {{- end }}
{{- end -}}