{{- define "common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name}}
type: Opaque
data:
  {{- if .Values.githubpass_enabled }}
  GITHUB_PASSWORD: {{ .Values.secret.githubPass }}
  {{- end }}
  {{- if .Values.githubpass_enabled }}
  GITHUB_PASSWORD: {{ .Values.secret.githubPass }}
  {{- end }}
  {{- if .Values.postgresuser_enabled }}
  POSTGRES_USER: {{ .Values.secret.postgresUser }}
  {{- end }}
  {{- if .Values.postgrespass_enabled }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPass }}
  {{- end }}
  {{- if .Values.dbuser_enabled }}
  DB_USER: {{ .Values.secret.dbUser }}
  {{- end }}
  {{- if .Values.dbpass_enabled }}
  DB_PASS: {{ .Values.secret.dbPass }}
  {{- end }}
{{- end -}}