{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }}
  labels:
    app: {{ .Values.deployment.label }}
spec:
  selector:
    app: {{ .Values.deployment.label }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: "{{ .Values.service.name }}"
  type: {{ .Values.service.type }}
{{- end -}}
  



